# serverless.yml

service: apollo-lambda
useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: index.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: false
    - http:
        path: graphql
        method: get
        cors: false